services:
  zabbix-server:
    image: ghcr.io/wuqiang0720/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: 192.168.125.100
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: zabbix

    ports:
      - "10051:10051"
    networks:
      zabbix-net:
        ipv4_address: 192.168.128.10

  zabbix-web:
    image: ghcr.io/wuqiang0720/zabbix-web-nginx-mysql:alpine-latest
    container_name: zabbix-web
    restart: always
    environment:
      DB_SERVER_HOST: 192.168.125.100
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Shanghai
    ports:
      - "8888:8080"
      - "9443:8443"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

  zabbix-agent:
    image: ghcr.io/wuqiang0720/zabbix-agent2cli:alpine-latest
    container_name: zabbix-agent
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: ubuntu-agent
    ports:
      - "10050:10050"
    networks:
      zabbix-net:
        ipv4_address: 192.168.128.5
    volumes:
      - ./zabbix_agent2.conf:/etc/zabbix/zabbix_agent2.conf
  collectd:
    image: ghcr.io/wuqiang0720/collectd:debian
    container_name: collectd
    restart: always
    networks:
      - zabbix-net
networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24
