services:
  mariadb-node1:
    image: ghcr.io/wuqiang0720/mariadb-galera:latest
    container_name: mariadb-node1
    restart: always
    networks:
      - galera-net
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://
      - MARIADB_GALERA_NODE_NAME=node1
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-node1,mariadb-node2,mariadb-node3
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes

    volumes:
      - mariadb_data1:/bitnami/mariadb

  mariadb-node2:
    image: ghcr.io/wuqiang0720/mariadb-galera:latest
    container_name: mariadb-node2
    restart: always
    networks:
      - galera-net
    ports:
      - "3308:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-node1,mariadb-node2,mariadb-node3
      - MARIADB_GALERA_NODE_NAME=node2
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-node2
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
    volumes:
      - mariadb_data2:/bitnami/mariadb

  mariadb-node3:
    image: ghcr.io/wuqiang0720/mariadb-galera:latest
    container_name: mariadb-node3
    restart: always
    networks:
      - galera-net
    ports:
      - "3309:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-node1,mariadb-node2,mariadb-node3
      - MARIADB_GALERA_NODE_NAME=node3
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-node3
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
    volumes:
      - mariadb_data3:/bitnami/mariadb
  haproxy:
    image: ghcr.io/wuqiang0720/haproxy:latest
    container_name: mariadb-haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "3306:3306"
    networks:
      - galera-net
networks:
  galera-net:
    driver: bridge
volumes:
  mariadb_data1:
  mariadb_data2:
  mariadb_data3:
