services:
  mariadb-node1:
    image: ghcr.io/wuqiang0720/mariadb-galera:10.5data
    container_name: mariadb-node1
    restart: always
    networks:
      - galera-net
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://
      - MARIADB_GALERA_NODE_NAME=node1
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-node1
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes

    volumes:
      - mariadb_data1:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-node2:
    image: ghcr.io/wuqiang0720/mariadb-galera:10.5data
    container_name: mariadb-node2
    restart: always
    networks:
      - galera-net
    ports:
      - "3308:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-node1,mariadb-node2,mariadb-node3
      - MARIADB_GALERA_NODE_NAME=node2
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-node2
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
    volumes:
      - mariadb_data2:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-node3:
    image: ghcr.io/wuqiang0720/mariadb-galera:10.5data
    container_name: mariadb-node3
    restart: always

    networks:
      - galera-net
    ports:
      - "3309:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-node1,mariadb-node2,mariadb-node3
      - MARIADB_GALERA_NODE_NAME=node3
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-node3
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
    volumes:
      - mariadb_data3:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  haproxy:
    image: ghcr.io/wuqiang0720/haproxy:mariadb
    container_name: mariadb-haproxy
    restart: always
    depends_on:
      - mariadb-node3
      - mariadb-node2
      - mariadb-node1
    ports:
      - "3306:3306"
    networks:
      - galera-net
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/3306' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6

  phpmyadmin:
    image: ghcr.io/wuqiang0720/phpmyadmin:latest
    container_name: mariadb-phpmyadmin
    restart: always
    environment:
      PMA_HOST: haproxy
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "80:80"
    depends_on:
      - haproxy
    networks:
      - galera-net
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6

networks:
  galera-net:
    driver: bridge
volumes:
  mariadb_data1:
  mariadb_data2:
  mariadb_data3:
