services:
  mariadb-node1:
    image: ghcr.io/wuqiang0720/mariadb-galera:10.5data
    container_name: mariadb-node1
    restart: on-failure
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.121
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://192.168.1.121,192.168.1.122,192.168.1.123
      - MARIADB_GALERA_NODE_NAME=node1
      - MARIADB_GALERA_NODE_ADDRESS=192.168.1.121
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes

    volumes:
      - mariadb_data1:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-node2:
    image: ghcr.io/wuqiang0720/mariadb-galera:10.5data
    container_name: mariadb-node2
    restart: on-failure
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.122
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://192.168.1.121,192.168.1.122,192.168.1.123
      - MARIADB_GALERA_NODE_NAME=node2
      - MARIADB_GALERA_NODE_ADDRESS=192.168.1.122
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
    volumes:
      - mariadb_data2:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      mariadb-node1:
        condition: service_healthy
  mariadb-node3:
    image: ghcr.io/wuqiang0720/mariadb-galera:10.5data
    container_name: mariadb-node3
    restart: on-failure
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.123
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_GALERA_CLUSTER_NAME=galera-cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://192.168.1.121,192.168.1.122,192.168.1.123
      - MARIADB_GALERA_NODE_NAME=node3
      - MARIADB_GALERA_NODE_ADDRESS=192.168.1.123
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup123
    volumes:
      - mariadb_data3:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      mariadb-node1:
        condition: service_healthy

  mariadb-haproxy:
    image: ghcr.io/wuqiang0720/haproxy:mariadb
    container_name: mariadb-haproxy
    restart: always
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.124
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/3306' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-phpadmin:
    image: ghcr.io/wuqiang0720/phpmyadmin:latest
    container_name: mariadb-phpadmin
    restart: always
    environment:
      PMA_HOST: 192.168.1.124
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.125
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      mariadb-haproxy:
        condition: service_healthy

networks:
  macvlan_net:
    external: true
volumes:
  mariadb_data1:
  mariadb_data2:
  mariadb_data3:
