FROM ghcr.io/wuqiang0720/alpine:3.20
RUN apk add --no-cache curl bash
COPY --from=ghcr.io/wuqiang0720/portainer/portainer-ce:latest / /
HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD curl -f http://localhost:9000 || exit 1
EXPOSE 9000/tcp
EXPOSE 9443/tcp
EXPOSE 8000/tcp
ENTRYPOINT ["/portainer"]

