version: "3.8"

services:
  uptime-kuma:
    image: ghcr.io/wuqiang0720/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    restart: always
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.50

networks:
  macvlan_net:
    external: true

volumes:
  uptime-kuma:
