services:
  openldap:
    image: ghcr.io/wuqiang0720/openldap:latest
    container_name: openldap-server
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_conf:/etc/ldap/slapd.d
    restart: unless-stopped
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.200
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/389' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  openldap-phpadmin:
    image: ghcr.io/wuqiang0720/phpldapadmin:https
    container_name: openldap-phpadmin
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    depends_on:
      - openldap
    restart: unless-stopped
    volumes:
      - phpldapadmin_data:/var/www/phpldapadmin
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.201
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
volumes:
  openldap_data:
  openldap_conf:
  phpldapadmin_data:
networks:
  macvlan_net:
    external: true
