services:
  openldap:
    image: ghcr.io/wuqiang0720/openldap:latest
    container_name: openldap
    environment:
      LDAP_TLS: "true"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_conf:/etc/ldap/slapd.d
    restart: unless-stopped
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.129

    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/389' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  phpldapadmin:
    image: ghcr.io/wuqiang0720/phpldapadmin:https
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap
    restart: unless-stopped
    volumes:
      - phpldapadmin_data:/var/www/phpldapadmin
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.130
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
volumes:
  openldap_data:
  openldap_conf:
  phpldapadmin_data:
networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: br-int
    ipam:
      config:
        - subnet: 192.168.1.128/28
          gateway: 192.168.1.131
