services:
  openldap:
    image: ghcr.io/wuqiang0720/openldap:latest
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_conf:/etc/ldap/slapd.d
    restart: unless-stopped

  phpldapadmin:
    image: ghcr.io/wuqiang0720/phpldapadmin:https
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
      - "6443:443"
    depends_on:
      - openldap
    restart: unless-stopped
    volumes:
      - phpldapadmin_data:/var/www/phpldapadmin
volumes:
  openldap_data:
  openldap_conf:
  phpldapadmin_data:
