name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.MY_GHCR_PAT }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/wuqiang0720/container-registry:latest

    - name: Make all GHCR packages public
      run: |
        echo "获取当前账号的所有 GHCR 容器包..."
        PACKAGES=$(gh api -H "Accept: application/vnd.github.v3+json" \
          /users/${{ github.repository_owner }}/packages?package_type=container \
          | jq -r '.[]?.name // .name')

        if [ -z "$PACKAGES" ]; then
          echo "❌ 没有找到任何容器包"
          exit 0
        fi

        echo "找到以下包，将全部设置为 public:"
        echo "$PACKAGES"

        for package in $PACKAGES; do
          echo "设置 $package 为 public ..."
          gh api -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            /users/${{ github.repository_owner }}/packages/container/$package/visibility \
            -f visibility=public
          echo "✅ $package 已设置为 public"
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}



