name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/wuqiang0720/container-registry:latest

    - name: Make latest package public
      run: |
        PACKAGE_NAME=$(gh api \
          -H "Accept: application/vnd.github.v3+json" \
          /users/${{ github.repository_owner }}/packages?package_type=container \
          | jq -r '.[0].name')

        echo "检测到最新的包: $PACKAGE_NAME"
        gh api \
          -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          /users/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME/visibility \
          -f visibility=public
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

