name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/wuqiang0720/container-registry:latest

    - name: Make pushed package public
      run: |
        # 从 tag 中提取 GHCR 包名
        IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/container-registry:latest"
        PACKAGE_NAME=$(echo "$IMAGE_TAG" | awk -F'/' '{print $2}' | awk -F':' '{print $1}')

        echo "检测到刚 push 的包: $PACKAGE_NAME"
        gh api \
          -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          /users/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME/visibility \
          -f visibility=public

        echo "✅ $PACKAGE_NAME 已设置为 public"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


