name: Build and Push Docker Images

on:
  workflow_dispatch:   # 手动触发，也可加 push trigger

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multiple images
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/image1:latest ./path-to-image1
          docker push ghcr.io/${{ github.repository_owner }}/image1:latest

          docker build -t ghcr.io/${{ github.repository_owner }}/image2:latest ./path-to-image2
          docker push ghcr.io/${{ github.repository_owner }}/image2:latest
