name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/wuqiang0720/container-registry:latest

    - name: Print GHCR tags
      env:
        GHCR_PAT: ${{ secrets.GHCR_PAT }}
      run: |
        curl -H "Authorization: Bearer $GHCR_PAT" \
             -H "Accept: application/vnd.github+json" \
             https://ghcr.io/v2/wuqiang0720/container-registry/tags/list
 


