name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/wuqiang0720/container-registry:latest

    - name: Make package public
      run: |
        PACKAGE_NAME="container-registry"
        USERNAME="${{ github.repository_owner }}"
        echo "设置 $PACKAGE_NAME 为 public ..."
        gh api \
          -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          /users/$USERNAME/packages/container/$PACKAGE_NAME/visibility \
          -f visibility=public
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
